### PR TITLE
Show custom property key as title 

### PR DESCRIPTION
**Pull request by rkpasia**

### CODE REVIEW

**Comment by rkpasia** [comment]
This could also be a fix for #198. I'm not able to reproduce a meaningful example for #198. Need help @tcompa

**Comment by tcompa** [comment]
Thanks @rkpasia, this is indeed the expected behavior for #201, since the key name is displayed on top of the value (e.g. "MyKey1", in the screenshot).

Screenshot from 2023-06-26 10-26-24

**Comment by tcompa** [comment]
As for #198, the behavior clearly improved, since we now see different descriptions for `channel` and `channel2` - see below.
What is currently wrong is that the titles are still not correct. They both display `Channel`, but they should match to the first-level argument names (as for the docstring), which are `channel` and `channel2`.

Screenshot from 2023-06-26 10-31-01

**Comment by rkpasia** [comment]
In order to see "channel2" as title for the property, it should be included in the nested schema. I mean:

Given the following partial schema
```json
"channel2": {
      "$ref": "#/definitions/Channel",
      "description": "Second channel for segmentation (in the same format as ``channel``). If specified, cellpose runs in dual channel mode.  For dual channel segmentation of cells, the first channel should contain the membrane marker, the second channel should contain the nuclear marker."
    },
```

If no `title` property is present in the inner `channel2` schema, then the default title in the referenced schema `#/definitions/Channel` is used.

Instead, if a `title` property is present in the inner schema as in the following
```json
"channel2": {
      "$ref": "#/definitions/Channel",
      "title": "Channel2",
      "description": "Second channel for segmentation (in the same format as ``channel``). If specified, cellpose runs in dual channel mode.  For dual channel segmentation of cells, the first channel should contain the membrane marker, the second channel should contain the nuclear marker."
    },
```

then the client will display "Channel2" as property title/name

**Comment by tcompa** [comment]
I see, thanks. Then this is a bit more work on the schema-generation side.

**Comment by rkpasia** [comment]
I could indeed show the property key `channel2` instead of the `title` property. But that isn't really by Json Schema design.

Moreover, this would require more logic to discriminate the property title:
- if there is a title property, then we should display the title
- if there is no title inside the root schema, but there is a reference, should the client display the title or the key?
- There would be situations in which is more helpful to display the key or the title?
- [...]

**Comment by tcompa** [comment]
> I could indeed show the property key channel2 instead of the title property.

I don't think fractal-web should do this. This is some more "custom" logic, which we will include in our schema-generation tools (in fractal-tasks-core). If a title is missing (as they are now), I'm OK with fractal-web not making any smart guess.

**Comment by tcompa** [comment]
Here are three relevant screenshots with comments

Screenshot 1: all as expected

Screenshot from 2023-06-26 11-48-03

Screenshot 2: all as expected. The argument descriptions may be improved (the higher-level one points to the lower-level one, and the lower-level one points to the higher-level one), but this has nothing to do with fractal-web.

Screenshot from 2023-06-26 11-48-30

Screenshot 3: all as expected, apart from a glitch (the "undefined" below `CHANNEL_KEY`). Is this something we can still fix @rkpasia?
Screenshot from 2023-06-26 11-48-51

**Comment by rkpasia** [comment]
> Screenshot 3: all as expected, apart from a glitch (the "undefined" below CHANNEL_KEY)


[af2d6e1](https://github.com/fractal-analytics-platform/fractal-web/pull/220/commits/af2d6e1e58060c74ea7df2a62e84a917eef99551) Should check it

**Comment by jluethi** [comment]
Looks good to me!

**Review by tcompa — APPROVED** [review]

**Pull request merged**
