### PR TITLE
Minor fixes in v0.3

### PR DESCRIPTION
**Pull request by rkpasia**
- #111 
- Fixes in breadcrumb
- #109
- #117

### CODE REVIEW

**Comment by rkpasia** [comment]
With this PR left open-issues in milestone v0.3 should be completed.

A few more clicks here and there could be helpful though! 👀 @tcompa @jluethi

**Comment by tcompa** [comment]
Thanks!

> A few more clicks here and there could be helpful though! eyes @tcompa @jluethi

I will go through the just-closed issues once again.

**Comment by rkpasia** [comment]
The one that should be checked a little more is #117.

There should be no more errors, but you never know 😇😂

**Comment by jluethi** [comment]
> The one that should be checked a little more is https://github.com/fractal-analytics-platform/fractal-web/issues/117.

Awesome! I'll rerun an example that uses this setup and check!

**Comment by jluethi** [comment]
> The one that should be checked a little more is https://github.com/fractal-analytics-platform/fractal-web/issues/117.

I can confirm that the lists with "0", "1", "2" objects now works as expected! 🎉

**Comment by jluethi** [comment]
Also confirming the breadcrumbs working correctly, the accessible job tables within the workflow and the showing pre-applied filters.

**Comment by tcompa** [comment]
I confirm the expected behavior for
* #111
* #109
* #117 

I opened a couple of other (minor) issues for glitches that I found:
* #125 
* #126

If these are easy to fix, may we have them as part of 0.3? If not, we can leave them in the backlog and move on.

**Comment by rkpasia** [comment]
I think we could include them in quick-fixes.

**Pull request merged**
