### PR TITLE
Improve JSchema component descriptions handling

### PR DESCRIPTION
**Pull request by rkpasia**

### CODE REVIEW

**Comment by tcompa** [comment]
Up to 87869e191856dda8b6073aab1b9f637c6d618978, it all looks good (still missing the description info button though):

Screenshot from 2023-06-27 11-19-57

**Comment by rkpasia** [comment]
Looking for feedbacks on wether the info icon is looking good placed where it is right now.

**Comment by tcompa** [comment]
Screenshot from 2023-06-27 11-42-46

**Comment by tcompa** [comment]
> Looking for feedbacks on wether the info icon is looking good placed where it is right now.

It does, for me.

Maybe the popover box can be a bit wider?

**Comment by jluethi** [comment]
This is great! =D

Regarding width: That is probably one of the largest descriptions shown above. For most descriptions, it will be shorter. Not against it being a bit wider though where possible & useful.

**Comment by jluethi** [comment]
I tested this branch myself now. 

It's a big improvement, makes the interface look much cleaner! And I like their behavior on showing on click, but disappearing when I click anything else.

I don't think we need the title "Argument description". Can we just drop the title, have only the description text?
And I agree they could be a bit wider. @rkpasia Can we make them 30% wider?

After that, let's merge this into main. I think it's a much better experience than showing the full description text and I'd like to deploy this version in both places :)

**Review by tcompa — APPROVED** [review]

**Comment by rkpasia** [comment]
The latest changes dropped the popover title and allowed the popover to span until 500px wide.
That's roughly 40% more than before.

I think we could close this one 👍🏼

**Comment by jluethi** [comment]
This is 🎉

Thanks @rkpasia !

Screenshot 2023-06-28 at 09 42 46

**Pull request merged**
