### PR TITLE
Quick layout fixes and iterations

### PR DESCRIPTION
**Pull request by rkpasia**

### CODE REVIEW

**Comment by rkpasia** [comment]
Inserted:
- Main layout heading
- Decreased workflow page main heading font size

**Comment by jluethi** [comment]
I like the removal of the `Main layout heading`, looks good!

Can we drop the workflow header entirely? i.e. the thing called `Workflow Workflow 2D_to_3D_workflow_2 #2`
Could also be dropped from the Project page and the dataset page. But there, it's not a big issue.

Screenshot 2023-06-26 at 14 17 54

**Comment by jluethi** [comment]
Awesome!

Screenshot 2023-06-26 at 14 20 26

**Comment by rkpasia** [comment]
Workflow page heading has been removed.
I've also fixed the breadcrumb in the page, that was an unnoticed (?) bug. Maybe we should check if there was any referencing issue about this @tcompa

**Comment by jluethi** [comment]
Yes, this issue here: https://github.com/fractal-analytics-platform/fractal-web/issues/214

I confirm that it's fixed now, great!

**Comment by jluethi** [comment]
For me, the last somewhat low-hanging fruit seems this part now:

Screenshot 2023-06-26 at 14 22 17

Best case, this could be compressed on a single line

**Comment by jluethi** [comment]
Also, the title of that element can be dropped. The "Workflow task Create OME-Zarr structure"

**Comment by rkpasia** [comment]
Ok, then #214 was the tracking issue about d68a5dc27faf5d08b65bd242478fa8be3e97ca16

**Review by jluethi — APPROVED** [review]
LTGM!

**Review by tcompa — APPROVED** [review]

**Pull request merged**
