### PR TITLE
Fix discard changes glitch and first-run glitch

### LINKED ISSUE #267: Fix glitch in task edit/delete/switch
How to reproduce:
- Create a Workflow
- Add WorkflowTask A
- Add WorkflowTask B
- Select task A in the list
- Edit arguments for A
- Click delete (top-right trash button)
- Confirm
- Select task B in the list (which is now the only one)
- A message appears, asking whether you want to discard previous changes (which were the changes to the already-deleted task A)

Expected behavior:
This message should not be there, since previous edits to task A are now irrelevant.

### LINKED ISSUE #313: First-run issues: Does not load some pages on first attempt
There's a weird behavior I've seen a few times in the past and now observed again when testing 0.6.0 (=> not new to 0.6.0):
When starting a fresh setup, sometimes the first time one clicks on certain pages, they don't load (they start loading, then send one back to the page one loaded from). The second time I load that page, everything works as expected.

For example: Create a project, submit a workflow. From the project page, go to the Jobs page. First time I do that, jobs page briefly flashes up, then project page reloads. Every following time, I get to the job page correctly.

Besides observing this in fresh installation, I don't have a way to reproduce it yet and not sure what exactly triggers this.

### PR DESCRIPTION
**Pull request by zonia3000**
## Checklist before merging
- [X] I added an appropriate entry to `CHANGELOG.md`

Closes #267 
Closes #313 (I'll leave a comment in the ticket)

### CODE REVIEW

**Comment by tcompa** [comment]
1. As per #313, I'll let @jluethi check that it works as expected.
2. I confirm that the bug described https://github.com/fractal-analytics-platform/fractal-web/issues/267#issue-1866739610 is fixed.
3. I'm trying to reproduce the bug that Joel showed us, but I'm not sure it is the same. Here's a reproducible procedure
    * Collect fractal-tasks-core tasks
    * Create a workflow, add the create-ome-zarr-multiplexing task, and select it.
    * Open the "Image Glob Patterns / Arguments list" accordion, and add one item to the list.
    * Do not click "save changes"
    * Open the "Allowed Channels / Argument Properties" accordion
    * Type a value for "key"
    * Click "Add property"
    * You'll get the "There are argument changes unsaved" modal

**Comment by tcompa** [comment]
To avoid collecting all fractal-tasks-core package, one can create a dummy task and set `args_schema` to
[args_schema.json](https://github.com/fractal-analytics-platform/fractal-web/files/12882469/args_schema.json)

**Comment by tcompa** [comment]
Some more info for debugging:

By adding `MODE="development"` in the appropriate env file, one can then head over at http://localhost:5173/sandbox/jsonschema and paste a JSON schema in the first text field to see something like
image


This does not include the save/discard logic, and then it's likely useless in this specific case, but I wanted to bring it up so that @zonia3000 is aware of it.

**Comment by zonia3000** [comment]
> 3. I'm trying to reproduce the bug that Joel showed us, but I'm not sure it is the same. Here's a reproducible procedure 

I've fixed this and potentially some similar ones. Some buttons (like the "Add property" one) missed the `type="button"` attribute, causing the form to automatically submit and then triggering the pending changes modal.

I've also displayed the error message in case of duplicated argument properties. It was currently silently logged in the console.

image

**Comment by tcompa** [comment]
> * I'm trying to reproduce the bug that Joel showed us, but I'm not sure it is the same. Here's a reproducible procedure
>   
>   * Collect fractal-tasks-core tasks
>   * Create a workflow, add the create-ome-zarr-multiplexing task, and select it.
>   * Open the "Image Glob Patterns / Arguments list" accordion, and add one item to the list.
>   * Do not click "save changes"
>   * Open the "Allowed Channels / Argument Properties" accordion
>   * Type a value for "key"
>   * Click "Add property"
>   * You'll get the "There are argument changes unsaved" modal

I confirm this issue is not present any more.

---

I also agree with the small error message for an already-present key:
image

**Comment by tcompa** [comment]
> I've fixed this and potentially some similar ones. Some buttons (like the "Add property" one) missed the type="button" attribute, causing the form to automatically submit and then triggering the pending changes modal.
> 
> I've also displayed the error message in case of duplicated argument properties. It was currently silently logged in the console.

Simultaneous comments ;)

Once again: I confirm the behavior is as expected, nothing to add from my side.

**Pull request merged**
