### PR TITLE
Added input filters tab on workflow page and improved dataset page

### LINKED ISSUE #437: Support adding `input_filters` to a V2 WorkflowTask
## Context

In V2, a WorkflowTask also has an attribute `input_filters`, which may look like
```json
{
  "types": {"is_3D": true},
  "attributes": {"well": "B03"}
}
```

This attribute is relevant for an advanced use case, where the user wants to override the default running flow of a workflow. By default, the runner selects which images will be processed based on the `task.input_types` and `dataset.filters` values, but if `workflowtask.input_types` is set then it takes highest priority.
Some use cases we have in mind:
1. The 3rd task of a workflow produces 2D images from 3D ones, thus setting `dataset.filters = {"type": {"is_3D": false}}`, but we want the 4th task to run on the original 3D images.
2. The user has converted a large multi-well plate to zarr, but they want to run a task on a single well. Caveat: this running modality is supported, but we did not review how it would look like e.g. in the workflow-task status.

## Feature

As a first version, we could do as follows:
1. We do not include `input_filters` in the task-insertion modal (that is, in the request body of the `POST /api/v2/project/{project_id}/workflow/{workflow_id}/wftask/` endpoint). This is mostly to avoid making the modal too complex (also in view of #1328), but if we find a nice way to include this option as a "hidden" advanced option I have nothing against it.
3. We treat the `workflowtask.input_filters` property in a dedicated tab (as we do for the "meta" properties):
    * The tab includes a form where `input_filters` can be modified, which then triggers a call to `PATCH /api/v2/project/{project_id}/workflow/{workflow_id}/wftask/{workflow_task_id}/`. Note that the structure of `input_filters` is the same as for `dataset.filters`: the `types` property is an object with boolean values, while the `attributes` property is an object with scalar non-null values.
    * Above the form, we include a brief explanation of when this attribute may be useful.

### LINKED ISSUE #441: Make dataset filters editable
As a user, I should be able to edit the current dataset filters.
For example, if there is a filter for is_3D = False, I should be able to remove this filter or set it for is_3D=True

### LINKED ISSUE #444: Deleting image list entries should inform that now images get deleted
It's very nice that we can edit the image list. The following dialogue is not very clear yet though:
Screenshot 2024-04-11 at 17 15 07

This appears as if the image data on disk would get deleted, but it's only about removing it from the database.

Suggested rewording:
In red box: "The following image is about to be removed from the Fractal image list: /path/to/image"

Below the red box:
"This does not remove the actual image data from disk, it just removes it from the Fractal database"
"Do you confirm?"

PS: We can of course discuss whether a future Fractal version would then be able to delete the actual image from disk as well. That would be non-trivial though (needs to be done as the user, not as Fractal), so let's not get into this now

### LINKED ISSUE #454: Something broken when using legacy tasks in V2?
I cannot fully explain this error, but I think I understand the main concept.

I am trying to access a dataset page after running a workflow where a legacy task was included.
The backend has no errors:
```
INFO:     127.0.0.1:54640 - "GET /api/v2/project/2/dataset/4/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:36202 - "POST /api/v2/project/2/dataset/4/images/query/?page=1&page_size=10 HTTP/1.1" 200 OK
```

However, the page http://localhost:5173/v2/projects/2/datasets/4 has the following browser-console error (and the spinner keeps going forever):
```
Uncaught (in promise) TypeError: ctx[2].workflowtask.task is null
    create_each_block DatasetHistoryModal.svelte:43
    create_if_block DatasetHistoryModal.svelte:139
    create_body_slot DatasetHistoryModal.svelte:333
    create_slot index.mjs:71
    create_fragment Modal.svelte:131
    init index.mjs:2137
    Modal Modal.svelte:560
    createProxiedComponent svelte-hooks.js:341
    ProxyComponent proxy.js:242
    Proxy<Modal> proxy.js:349
    create_fragment DatasetHistoryModal.svelte:390
    init index.mjs:2137
    DatasetHistoryModal DatasetHistoryModal.svelte:512
    createProxiedComponent svelte-hooks.js:341
    ProxyComponent proxy.js:242
    Proxy<DatasetHistoryModal> proxy.js:349
    create_fragment +page.svelte:2117
    init index.mjs:2137
    Page +page.svelte:2898
    createProxiedComponent svelte-hooks.js:341
    ProxyComponent proxy.js:242
    Proxy<+page> proxy.js:349
    construct_svelte_component_dev index.mjs:2355
    update root.svelte:288
    update root.svelte:557
    update_slot_base index.mjs:100
    update +layout.svelte:1172
    update index.mjs:1298
    flush index.mjs:1258
    promise callback*schedule_update index.mjs:1209
    make_dirty index.mjs:2090
    ctx index.mjs:2128
    $$set root.svelte:924
    get proxy.js:83
    $set index.mjs:2229
    key proxy.js:46
    navigate client.js:1108
    _start_router client.js:1590
    _start_router client.js:1508
    start start.js:27
    async* tasks:475
    promise callback* tasks:474
DatasetHistoryModal.svelte:43:14
```

I cannot point to a specific fix, but the most relevant piece of information here is the following:
In V2, WorkflowTask objects have either the `task` properties set (and `task_legacy=null`, and `is_legacy_task=false`) or `task_legacy` set (and `task=null` and `is_legacy_task=true`).

This is also related to backend issues (https://github.com/fractal-analytics-platform/fractal-server/issues/1390, and similar to https://github.com/fractal-analytics-platform/fractal-server/issues/1405), but perhaps it still needs work on the frontend side.

### PR DESCRIPTION
**Pull request by zonia3000**
## Checklist before merging
- [X] I added an appropriate entry to `CHANGELOG.md`

Ref #428
Close #454
Closes #444
Closes #441
Closes #437
Closes #454

### CODE REVIEW

**Comment by tcompa** [comment]
This looks great!

**Comment by tcompa** [comment]
There is a tiny unclear detail I spotted in the pagination section.

I start with
image

Then I click on "11", and the page changes correctly, but "12" is highlighted in gray:
image

Is this the expected behavior?

**Comment by tcompa** [comment]
Another minor glitch.

I start with
image

Then I select a given well in the dropdown menu (without clicking apply), and the size of some element changes
image

This triggers a small layout change, which moves the columns horizontally - and it looks like something is happening in the data.


Would it be doable to keep the size fixed, when selecting e.g. well=A90?

**Comment by tcompa** [comment]
Another tiny glitch in the dropdown menus:

Either the true or false row should be highlighted, but not both at the same time.

image

image

**Comment by tcompa** [comment]
When I try to edit the `zarr_dirr` but receive a 422 from the backend, the spinner keeps going forever

image

**Comment by tcompa** [comment]
Within the dataset-filters modal:
image

The attribute values can be strings, numbers or boolean (boolean is currently missing).

**Comment by tcompa** [comment]
> The attribute values can be strings, numbers or boolean (boolean is currently missing).

This also applies to the new workflow-task input-filters tab:
image

**Comment by zonia3000** [comment]
> Another tiny glitch in the dropdown menus:
> Either the true or false row should be highlighted, but not both at the same time.
> image

Changed the hover background color of slim-select to light grey. This applies globally, not only in this page.

image

**Comment by zonia3000** [comment]
> When I try to edit the `zarr_dirr` but receive a 422 from the backend, the spinner keeps going forever
> 
> image

Handled this case:

image

**Comment by jluethi** [comment]
> I can do this only setting a fixed width to the dropdowns. I would set 180px for attributes and 100px for types. This has an implication on the columns that have a long name in the header.

I like this new option 1 much better! Makes for more horizontal compactness. We may have some attributes that are 2 lines long, but probably most won't be :)

**Comment by tcompa** [comment]
I confirm that after https://github.com/fractal-analytics-platform/fractal-web/commit/6d62eb12c2db35191229643fa1e03307bc4ff822 fixes the bug I just spotted is not there any more, thanks.

**Pull request merged**
