### PR TITLE
Fixed argument popovers performance issue

### PR DESCRIPTION
**Pull request by zonia3000**
## Checklist before merging
- [X] I added an appropriate entry to `CHANGELOG.md`

I've run the Firefox profiler using the workflow file provided by @jluethi in #322.

It detects that the performance issue is related to the file `PropertyDescription.svelte`:

Screenshot from 2023-10-24 08-50-18

That component displays the description of each argument inside a popover. However it was initializing every time all the popovers of the page for each component, resulting in a huge number of popover initialization. With this PR only the popover contained in the component is initialized.

### CODE REVIEW

**Comment by zonia3000** [comment]
Some comments about the following message:

```
vite:istanbul> Sourcemaps was automatically enabled for code coverage to be accurate.
 To hide this message set build.sourcemap to true, 'inline' or 'hidden'.
```

Sourcemaps files are usually generated during the build and they are useful for debugging purposes, as well as for the coverage. It looks that istanbul plugin run always, not only during tests. It checks if vite is configured to build the sourcemap files and if it is not it automatically enables that feature.

I added the following to vite.config.js to always enable the building of sourcemaps, since they can be useful also for debugging and I don't think they can have an impact on performance on production code, since they are loaded by the browser only if the developer tools are enabled:

```
build: {
  sourcemap: true
}
```

As a side effect, this also hides that warning.

In any case I don't like the fact that istanbul plugin is always loaded, so I introduced an environment variable `ENABLE_COVERAGE` that has to be set to true to enable istanbul. I updated the pipeline files to have it enabled in our tests.

**Comment by tcompa** [comment]
Thanks @zonia3000!

I'd just need a quick clarification, because we may be using different dictionaries here ;)
Here is mine:
* We load the page corresponding to a given `Workflow` (e.g. the one with ID=8)
* The `task_list` includes a list of `WorkflowTask` objects, each one with its own ID
* Each `WorkflowTask` has a `task` property (which is a `Task` object), and `WorkflowTask.task` also has its own ID
* The `WorkflowTask.task.args_schema` (optional) property is a JSON Schema that describes the N arguments of a given task, possibly in a nested form (an argument may be an array/object itself).
* When we select a given `WorkflowTask` from the `task_list`, a fractal-web component prepares the form to fill/update its arguments, based on `WorkflowTask.task.args_schema`.

You say:
> However it was initializing every time all the popovers of the page for each component, resulting in a huge number of popover initialization. With this PR only the popover contained in the component is initialized.

and this is how I interpret it:
> it was initializing every time all the popovers of the page for all the components (that is, for all the arguments of all `WorkflowTask`s in `task_list`), resulting in a huge number of popover initialization. With this PR only the N popovers related to the currently-selected `WorkflowTask` are initialized.

Am I getting this right?

**Comment by tcompa** [comment]
And thanks for the clarification re:Istabul.

**Comment by zonia3000** [comment]
> > it was initializing every time all the popovers of the page for all the components (that is, for all the arguments of all `WorkflowTask`s in `task_list`), resulting in a huge number of popover initialization. With this PR only the N popovers related to the currently-selected `WorkflowTask` are initialized.
> 
> Am I getting this right?

Yes, I mean these popovers (generated by the `PropertyDescription`  component):

image

Previously each `PropertyDescription` component initialized all the popovers of the page (in the case of the problematic tasks it happened 319 x 319 times).

Now each `PropertyDescription` component initialize only its own component (so in that case we now initialize them 319 x 1 times).

**Comment by tcompa** [comment]
OK, thanks again.

It'd be useful, just for once, to understand where does 319 come from. I'll try to have a simple example, and maybe you can confirm if it makes sense

Here is a simplified JSON Schema, related to the original one:
```json
{
    "title": "CreateOmeZarrMultiplex",
    "type": "object",
    "properties": {
        "allowed_channels": {
            "title": "Allowed Channels",
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "$ref": "#/definitions/OmeroChannel"
                }
            },
            "description": "DESCRIPTION A"
        }
    },
    "required": [
        "allowed_channels"
    ],
    "additionalProperties": false,
    "definitions": {
        "OmeroChannel": {
            "title": "OmeroChannel",
            "description": "DESCRIPTION B",
            "type": "string"
        }
    }
}
```
and here are some data
```json
{
    "allowed_channels": {
        "key1": [
            "A",
            "B",
            "C"
        ],
        "key2": [
            "D",
            "E",
            "F"
        ]
    }
}
```

Based on the screenshot below, I guess we should be initializing 7 popovers: one for "Allowed Channels" and then six for the items corresponding to A,B,C,D,E,F. And, if I understand correctly, before this PR we would initialize 7x7=49 popovers.
Is this correct?

image

**Review by tcompa — APPROVED** [review]

**Comment by zonia3000** [comment]
I didn't retrieved the number in an analytical way. I've just run the following in the browser console:

image

You can expand the first and the last elements and see that they are all popovers from that task arguments.

In any case, your reasoning is correct.

**Comment by tcompa** [comment]
> I've just run the following in the browser console:
> 
> image

Thanks, I confirm it shows 7 nodes in my case (and they can be clearly identified):
image

**Pull request merged**
